name: Zstd package build

on:
  push:
    branches:
      - main
env:
  GITHUB_USERNAME: dakkshesh07
  GITHUB_EMAIL: dakkshesh5@gmail.com
  PACK_VER_SHORT: 1.5.2
  PACK_REL: 8
  GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
          gh auth login --with-token <<< $GHUB_TOKEN
      - name: Build Test
        run: |
          curl -fsSL "https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static" -o pacman-static && chmod +x pacman-static && mv pacman-static /usr/bin/
          pacman-static -Syu --needed --noconfirm gtest
          sed -i '/E_ROOT/d' /usr/bin/makepkg && env PKG_VER=$PACK_VER_SHORT PKG_REL=$PACK_REL makepkg -s
          git clone https://github.com/dakkshesh07/zstd-pkgbuild.git zstd-repo
          mv *.pkg.tar.zst zstd-repo/
          cd zstd-repo/
          export PACK_VER="$PACK_VER_SHORT-$PACK_REL"
          curl -s https://bin.cyberknight777.dev/ojhW/raw | bash
